"""empty message

Revision ID: 7c9762e9b9ed
Revises: 63af3cbc94ba
Create Date: 2019-10-28 09:32:29.212418

"""

# revision identifiers, used by Alembic.
revision = '7c9762e9b9ed'
down_revision = '63af3cbc94ba'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
