"""empty message

Revision ID: 95a1d7ef9ece
Revises: c32f98a97089
Create Date: 2019-10-24 16:15:17.863694

"""

# revision identifiers, used by Alembic.
revision = '95a1d7ef9ece'
down_revision = 'c32f98a97089'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_hash', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_hash')
    # ### end Alembic commands ###
